"""Add is_approved field to users table

Revision ID: 3c2cf4c5bd5e
Revises: 
Create Date: 2025-11-09 00:56:20.134626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2cf4c5bd5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Make migration idempotent - only add column if it doesn't exist
    from sqlalchemy import inspect
    from sqlalchemy.exc import NoSuchTableError

    conn = op.get_bind()
    inspector = inspect(conn)

    try:
        columns = [col['name'] for col in inspector.get_columns('users')]

        if 'is_approved' not in columns:
            op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=True))
    except NoSuchTableError:
        # Table doesn't exist yet, skip this migration
        # It will be created by the initial migration
        print("INFO: users table does not exist yet, skipping is_approved column addition")
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_approved')
    # ### end Alembic commands ###
