"""Add created_by_client_id field to track which client created a player

Revision ID: 5d108f810415
Revises: 3c2cf4c5bd5e
Create Date: 2025-11-09 01:58:16.657387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d108f810415'
down_revision: Union[str, Sequence[str], None] = '3c2cf4c5bd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by_client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by_client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by_client_id')
    # ### end Alembic commands ###
