"""Add game_link and custom_image_url to client_games

Revision ID: cb66b4d9f97d
Revises: 3363b800be94
Create Date: 2025-12-25 20:11:59.007754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb66b4d9f97d'
down_revision: Union[str, Sequence[str], None] = '3363b800be94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_games', sa.Column('game_link', sa.String(), nullable=True))
    op.add_column('client_games', sa.Column('custom_image_url', sa.String(), nullable=True))
    op.add_column('client_games', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_games', 'updated_at')
    op.drop_column('client_games', 'custom_image_url')
    op.drop_column('client_games', 'game_link')
    # ### end Alembic commands ###
