"""Add moderation fields to users reviews and reports

Revision ID: ed2a99bae37f
Revises: 3951f4e922aa
Create Date: 2026-01-04 04:18:11.095786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2a99bae37f'
down_revision: Union[str, Sequence[str], None] = '3951f4e922aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('evidence', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('action_taken', sa.String(length=500), nullable=True))
    op.add_column('reports', sa.Column('appeal_ticket_id', sa.Integer(), nullable=True))
    op.alter_column('reports', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'INVESTIGATING', 'VALID', 'INVALID', 'MALICIOUS', name='reportstatus'),
               existing_nullable=True)
    op.create_foreign_key(None, 'reports', 'tickets', ['appeal_ticket_id'], ['id'])
    op.add_column('reviews', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'DISPUTED', name='reviewstatus'), nullable=False))
    op.add_column('reviews', sa.Column('moderated_by', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reviews', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('appeal_ticket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'tickets', ['appeal_ticket_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'users', ['moderated_by'], ['id'])
    op.alter_column('tickets', 'category',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('ACCOUNT', 'PAYMENT', 'TECHNICAL', 'PROMOTION', 'REPORT_USER', 'FEEDBACK', 'APPEAL_REVIEW', 'APPEAL_REPORT', 'OTHER', name='ticketcategory'),
               existing_nullable=False)
    op.add_column('users', sa.Column('malicious_reports_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_trusted_reviewer', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('suspension_reason', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('suspended_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'suspended_until')
    op.drop_column('users', 'suspension_reason')
    op.drop_column('users', 'is_suspended')
    op.drop_column('users', 'is_trusted_reviewer')
    op.drop_column('users', 'malicious_reports_count')
    op.alter_column('tickets', 'category',
               existing_type=sa.Enum('ACCOUNT', 'PAYMENT', 'TECHNICAL', 'PROMOTION', 'REPORT_USER', 'FEEDBACK', 'APPEAL_REVIEW', 'APPEAL_REPORT', 'OTHER', name='ticketcategory'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'appeal_ticket_id')
    op.drop_column('reviews', 'admin_notes')
    op.drop_column('reviews', 'moderated_at')
    op.drop_column('reviews', 'moderated_by')
    op.drop_column('reviews', 'status')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.alter_column('reports', 'status',
               existing_type=sa.Enum('PENDING', 'INVESTIGATING', 'VALID', 'INVALID', 'MALICIOUS', name='reportstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.drop_column('reports', 'appeal_ticket_id')
    op.drop_column('reports', 'action_taken')
    op.drop_column('reports', 'evidence')
    # ### end Alembic commands ###
